name: Build Jupyter Images
  
on:
  push:
    branches:
      - master

jobs:
  create_image:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Compile and push docker images
        run: ./actions.sh
