name: Build Jupyter Images
  
on:
  push:
    branches:
      - master
    paths:
      - 'jupyter_lab/**'
      - 'jupyter_notebook/**'

jobs:
  create_image:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Compile and push docker images
        run: ./actions.sh
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
      